import json

# ============================================================
# Patch BOTH notebooks: Add metrics + Optimize speed
# ============================================================

for nb_file in ['MVS_XAI_Colab_DataPrep_Phase1.ipynb', 'MVS_XAI_Colab_IEEE_CIS.ipynb']:
    with open(nb_file, 'r', encoding='utf-8') as f:
        nb = json.load(f)

    is_paysim = 'Phase1' in nb_file
    ds_name = 'PaySim' if is_paysim else 'IEEE-CIS'

    for cell in nb['cells']:
        if cell['cell_type'] != 'code':
            continue
        cell_id = cell.get('metadata', {}).get('id', '')

        # ============================================================
        # 1. OPTIMIZE OOF: Train ONCE, predict TWICE
        # ============================================================
        if cell_id == 'oof_gen':
            if is_paysim:
                cell['source'] = [
                    "def generate_oof_train(X_tab_tr, y_smote, X_seq_tr, y_raw, X_grp_tr):\n",
                    "    \"\"\"Train 5 models ONCE. Return trained models.\"\"\"\n",
                    "    print('    [RF] Training...')\n",
                    "    rf = RandomForestClassifier(100, max_depth=15, n_jobs=-1, random_state=42)\n",
                    "    rf.fit(X_tab_tr, y_smote)\n",
                    "    print('    [XGB] Training...')\n",
                    "    xc = xgb.XGBClassifier(n_estimators=500, max_depth=8, learning_rate=0.05,\n",
                    "        tree_method='hist', device='cuda',\n",
                    "        colsample_bytree=0.7, subsample=0.8, random_state=42, n_jobs=-1)\n",
                    "    xc.fit(X_tab_tr, y_smote)\n",
                    "    print('    [LGB] Training...')\n",
                    "    lc = lgb.LGBMClassifier(n_estimators=500, max_depth=12, learning_rate=0.05,\n",
                    "        colsample_bytree=0.7, subsample=0.8,\n",
                    "        random_state=42, n_jobs=-1, verbose=-1)\n",
                    "    lc.fit(X_tab_tr, y_smote)\n",
                    "    print('    [LSTM] Training...')\n",
                    "    lstm_model = build_lstm(X_seq_tr.shape[1], X_seq_tr.shape[2])\n",
                    "    lstm_model.fit(X_seq_tr, y_raw, epochs=15, batch_size=2048, verbose=0,\n",
                    "                  class_weight={0:1, 1:max(1, int((y_raw==0).sum()/(y_raw==1).sum()))})\n",
                    "    print('    [GAT] Training...')\n",
                    "    gat_model = build_gat(X_grp_tr.shape[1])\n",
                    "    gat_model.fit(X_grp_tr, y_raw, epochs=50, batch_size=2048, verbose=0,\n",
                    "                  class_weight={0:1, 1:max(1, int((y_raw==0).sum()/(y_raw==1).sum()))})\n",
                    "    return rf, xc, lc, lstm_model, gat_model\n",
                    "\n",
                    "def predict_oof(models, X_tab, X_seq, X_grp):\n",
                    "    \"\"\"Predict with trained models. No re-training!\"\"\"\n",
                    "    rf, xc, lc, lstm_m, gat_m = models\n",
                    "    n = X_tab.shape[0]\n",
                    "    oof = np.zeros((n, 5))\n",
                    "    oof[:,0] = rf.predict_proba(X_tab)[:,1]\n",
                    "    oof[:,1] = xc.predict_proba(X_tab)[:,1]\n",
                    "    oof[:,2] = lc.predict_proba(X_tab)[:,1]\n",
                    "    oof[:,3] = lstm_m.predict(X_seq, batch_size=4096, verbose=0).ravel()\n",
                    "    oof[:,4] = gat_m.predict(X_grp, batch_size=4096, verbose=0).ravel()\n",
                    "    print(f'    OOF shape: {oof.shape}')\n",
                    "    return oof, lc\n",
                ]
            else:
                # IEEE-CIS version
                cell['source'] = [
                    "def generate_oof_train(X_tab_tr, y_smote, X_seq_tr, y_raw, X_grp_tr):\n",
                    "    \"\"\"Train 5 models ONCE. Return trained models.\"\"\"\n",
                    "    print('    [RF] Training...')\n",
                    "    rf = RandomForestClassifier(100, max_depth=15, n_jobs=-1, random_state=42)\n",
                    "    rf.fit(X_tab_tr, y_smote)\n",
                    "    print('    [XGB] Training...')\n",
                    "    xc = xgb.XGBClassifier(n_estimators=500, max_depth=8, learning_rate=0.05,\n",
                    "        tree_method='hist', device='cuda',\n",
                    "        colsample_bytree=0.7, subsample=0.8, random_state=42, n_jobs=-1)\n",
                    "    xc.fit(X_tab_tr, y_smote)\n",
                    "    print('    [LGB] Training...')\n",
                    "    lc = lgb.LGBMClassifier(n_estimators=500, max_depth=12, learning_rate=0.05,\n",
                    "        colsample_bytree=0.7, subsample=0.8,\n",
                    "        random_state=42, n_jobs=-1, verbose=-1)\n",
                    "    lc.fit(X_tab_tr, y_smote)\n",
                    "    print('    [LSTM] Training...')\n",
                    "    lstm_model = build_lstm(X_seq_tr.shape[1], X_seq_tr.shape[2])\n",
                    "    lstm_model.fit(X_seq_tr, y_raw, epochs=15, batch_size=2048, verbose=0,\n",
                    "                  class_weight={0:1, 1:max(1, int((y_raw==0).sum()/(y_raw==1).sum()))})\n",
                    "    print('    [GAT] Training...')\n",
                    "    gat_model = build_gat(X_grp_tr.shape[1])\n",
                    "    gat_model.fit(X_grp_tr, y_raw, epochs=50, batch_size=2048, verbose=0,\n",
                    "                  class_weight={0:1, 1:max(1, int((y_raw==0).sum()/(y_raw==1).sum()))})\n",
                    "    return rf, xc, lc, lstm_model, gat_model\n",
                    "\n",
                    "def predict_oof(models, X_tab, X_seq, X_grp):\n",
                    "    \"\"\"Predict with trained models. No re-training!\"\"\"\n",
                    "    rf, xc, lc, lstm_m, gat_m = models\n",
                    "    n = X_tab.shape[0]\n",
                    "    oof = np.zeros((n, 5))\n",
                    "    oof[:,0] = rf.predict_proba(X_tab)[:,1]\n",
                    "    oof[:,1] = xc.predict_proba(X_tab)[:,1]\n",
                    "    oof[:,2] = lc.predict_proba(X_tab)[:,1]\n",
                    "    oof[:,3] = lstm_m.predict(X_seq, batch_size=4096, verbose=0).ravel()\n",
                    "    oof[:,4] = gat_m.predict(X_grp, batch_size=4096, verbose=0).ravel()\n",
                    "    print(f'    OOF shape: {oof.shape}')\n",
                    "    return oof, lc\n",
                ]
            print(f'  [{ds_name}] OOF: Train-once, predict-twice')

        # ============================================================
        # 2. PIPELINE: Use train-once + Add detailed metrics
        # ============================================================
        if cell_id == 'run_pipeline':
            if is_paysim:
                cell['source'] = [
                    "from sklearn.metrics import classification_report, confusion_matrix, f1_score, precision_score, recall_score\n",
                    "import time as _time\n",
                    "\n",
                    "# ====== STAGE 1 ======\n",
                    "t_start = _time.time()\n",
                    "df_proc, scaler = stage1_preprocessing(df_raw)\n",
                    "del df_raw; import gc; gc.collect()\n",
                    "\n",
                    "# ====== STAGE 3 ======\n",
                    "print('\\n[Stage 3] Multi-View Feature Engineering...')\n",
                    "X_tab = extract_tabular_view(df_proc)\n",
                    "X_seq = extract_sequential_view(df_proc)\n",
                    "X_grp, gcols = extract_graph_view(df_proc)\n",
                    "y = df_proc['isFraud'].values\n",
                    "df_meta = df_proc[['amount']].copy() if 'amount' in df_proc.columns else None\n",
                    "del df_proc; gc.collect()\n",
                    "print('  Data arrays ready. Memory freed.')\n",
                    "\n",
                    "# ====== STAGE 2: 5-Block Walk-Forward CV ======\n",
                    "print('\\n[Stage 2] 5-Block Walk-Forward CV...')\n",
                    "tscv = TimeSeriesSplit(n_splits=5)\n",
                    "fold_metrics = []\n",
                    "\n",
                    "for fold, (tr_i, vl_i) in enumerate(tscv.split(X_tab)):\n",
                    "    t_fold = _time.time()\n",
                    "    print(f'\\n{\"=\"*60}\\nFOLD {fold+1}/5\\n{\"=\"*60}')\n",
                    "    Xt_tr, Xt_vl = X_tab[tr_i], X_tab[vl_i]\n",
                    "    Xs_tr, Xs_vl = X_seq[tr_i], X_seq[vl_i]\n",
                    "    Xg_tr, Xg_vl = X_grp[tr_i], X_grp[vl_i]\n",
                    "    y_tr, y_vl = y[tr_i], y[vl_i]\n",
                    "\n",
                    "    # SMOTE on Tabular\n",
                    "    print('  [SMOTE] K-Means SMOTE on Tabular branch...')\n",
                    "    try:\n",
                    "        sm = KMeansSMOTE(cluster_balance_threshold=0.1, random_state=42)\n",
                    "        Xt_sm, y_sm = sm.fit_resample(Xt_tr, y_tr)\n",
                    "    except:\n",
                    "        Xt_sm, y_sm = SMOTE(random_state=42).fit_resample(Xt_tr, y_tr)\n",
                    "    print(f'    After SMOTE: {Xt_sm.shape[0]} (was {Xt_tr.shape[0]})')\n",
                    "\n",
                    "    # Stage 4: Train ONCE\n",
                    "    print('  [Stage 4] Training models...')\n",
                    "    models = generate_oof_train(Xt_sm, y_sm, Xs_tr, y_tr, Xg_tr)\n",
                    "    # Predict on val and train (NO re-training!)\n",
                    "    print('  [Stage 4] Predicting OOF (val)...')\n",
                    "    oof_vl, best_lgb = predict_oof(models, Xt_vl, Xs_vl, Xg_vl)\n",
                    "    print('  [Stage 4] Predicting OOF (train)...')\n",
                    "    oof_tr, _ = predict_oof(models, Xt_tr, Xs_tr, Xg_tr)\n",
                    "\n",
                    "    # Stage 5: Meta\n",
                    "    meta, meta_p = stage5_meta(oof_tr, y_tr, oof_vl)\n",
                    "    auprc = average_precision_score(y_vl, meta_p)\n",
                    "    roc = roc_auc_score(y_vl, meta_p)\n",
                    "\n",
                    "    # Detailed metrics at optimal threshold\n",
                    "    y_pred = (meta_p >= 0.5).astype(int)\n",
                    "    f1 = f1_score(y_vl, y_pred, zero_division=0)\n",
                    "    prec = precision_score(y_vl, y_pred, zero_division=0)\n",
                    "    rec = recall_score(y_vl, y_pred, zero_division=0)\n",
                    "\n",
                    "    fold_time = _time.time() - t_fold\n",
                    "    fold_metrics.append({'Fold': fold+1, 'AUPRC': auprc, 'ROC-AUC': roc,\n",
                    "                         'F1': f1, 'Precision': prec, 'Recall': rec,\n",
                    "                         'Time_min': fold_time/60})\n",
                    "    print(f'  FOLD {fold+1}: AUPRC={auprc:.4f}, ROC-AUC={roc:.4f}, F1={f1:.4f}, P={prec:.4f}, R={rec:.4f} ({fold_time/60:.1f}min)')\n",
                    "    del Xt_sm, y_sm; gc.collect()\n",
                    "\n",
                    "    if fold == 4:\n",
                    "        print(f'\\n{\"=\"*60}\\nFOLD 5 (FINAL): Detailed Metrics + XAI\\n{\"=\"*60}')\n",
                    "        print('\\n--- Classification Report ---')\n",
                    "        print(classification_report(y_vl, y_pred, target_names=['Normal', 'Fraud']))\n",
                    "        print('--- Confusion Matrix ---')\n",
                    "        cm = confusion_matrix(y_vl, y_pred)\n",
                    "        print(f'  TN={cm[0,0]:,}  FP={cm[0,1]:,}')\n",
                    "        print(f'  FN={cm[1,0]:,}  TP={cm[1,1]:,}')\n",
                    "        print(f'\\n--- Threshold Analysis ---')\n",
                    "        for t in [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]:\n",
                    "            yt = (meta_p >= t).astype(int)\n",
                    "            print(f'  t={t:.1f}: F1={f1_score(y_vl, yt, zero_division=0):.4f}, '\n",
                    "                  f'P={precision_score(y_vl, yt, zero_division=0):.4f}, '\n",
                    "                  f'R={recall_score(y_vl, yt, zero_division=0):.4f}')\n",
                    "\n",
                    "        # XAI\n",
                    "        Xs = Xt_vl[:200]\n",
                    "        top3 = stage6_xai(best_lgb, Xt_tr[:2000], Xs, TABULAR_FEATURES)\n",
                    "        stage7_dual_output(meta_p, top3, y_vl)\n",
                    "        if df_meta is not None:\n",
                    "            stage8_hitl(meta_p, df_meta.iloc[vl_i])\n",
                    "\n",
                    "# ====== SUMMARY ======\n",
                    "total_time = (_time.time() - t_start) / 60\n",
                    "print(f'\\n{\"=\"*60}\\nMVS-XAI PaySim Pipeline Complete\\n{\"=\"*60}')\n",
                    "mdf = pd.DataFrame(fold_metrics)\n",
                    "print(mdf.to_string(index=False))\n",
                    "print(f'\\nMean AUPRC:   {mdf[\"AUPRC\"].mean():.4f} +/- {mdf[\"AUPRC\"].std():.4f}')\n",
                    "print(f'Mean ROC-AUC: {mdf[\"ROC-AUC\"].mean():.4f} +/- {mdf[\"ROC-AUC\"].std():.4f}')\n",
                    "print(f'Mean F1:      {mdf[\"F1\"].mean():.4f} +/- {mdf[\"F1\"].std():.4f}')\n",
                    "print(f'Mean Prec:    {mdf[\"Precision\"].mean():.4f} +/- {mdf[\"Precision\"].std():.4f}')\n",
                    "print(f'Mean Recall:  {mdf[\"Recall\"].mean():.4f} +/- {mdf[\"Recall\"].std():.4f}')\n",
                    "print(f'Total runtime: {total_time:.1f} min')\n",
                ]
            else:
                # IEEE-CIS version
                cell['source'] = [
                    "from sklearn.metrics import classification_report, confusion_matrix, f1_score, precision_score, recall_score\n",
                    "import time as _time\n",
                    "\n",
                    "# ====== STAGE 1 ======\n",
                    "t_start = _time.time()\n",
                    "df_proc, scaler = stage1_preprocessing(df_raw)\n",
                    "del df_raw; import gc; gc.collect()\n",
                    "\n",
                    "# ====== STAGE 3 ======\n",
                    "print('\\n[Stage 3] Multi-View Feature Engineering...')\n",
                    "selected = select_tabular_features(df_proc)\n",
                    "X_tab = extract_tabular_view(df_proc, selected)\n",
                    "X_seq = extract_sequential_view(df_proc)\n",
                    "X_grp, gcols = extract_graph_view(df_proc)\n",
                    "y = df_proc['isFraud'].values\n",
                    "df_meta = df_proc[['TransactionAmt']].copy() if 'TransactionAmt' in df_proc.columns else None\n",
                    "del df_proc; gc.collect()\n",
                    "print('  Data arrays ready. Memory freed.')\n",
                    "\n",
                    "# ====== STAGE 2: 5-Block Walk-Forward CV ======\n",
                    "print('\\n[Stage 2] 5-Block Walk-Forward CV...')\n",
                    "tscv = TimeSeriesSplit(n_splits=5)\n",
                    "fold_metrics = []\n",
                    "\n",
                    "for fold, (tr_i, vl_i) in enumerate(tscv.split(X_tab)):\n",
                    "    t_fold = _time.time()\n",
                    "    print(f'\\n{\"=\"*60}\\nFOLD {fold+1}/5\\n{\"=\"*60}')\n",
                    "    Xt_tr, Xt_vl = X_tab[tr_i], X_tab[vl_i]\n",
                    "    Xs_tr, Xs_vl = X_seq[tr_i], X_seq[vl_i]\n",
                    "    Xg_tr, Xg_vl = X_grp[tr_i], X_grp[vl_i]\n",
                    "    y_tr, y_vl = y[tr_i], y[vl_i]\n",
                    "\n",
                    "    # SMOTE on Tabular\n",
                    "    print('  [SMOTE] K-Means SMOTE on Tabular branch...')\n",
                    "    try:\n",
                    "        sm = KMeansSMOTE(cluster_balance_threshold=0.1, random_state=42)\n",
                    "        Xt_sm, y_sm = sm.fit_resample(Xt_tr, y_tr)\n",
                    "    except:\n",
                    "        Xt_sm, y_sm = SMOTE(random_state=42).fit_resample(Xt_tr, y_tr)\n",
                    "    print(f'    After SMOTE: {Xt_sm.shape[0]} (was {Xt_tr.shape[0]})')\n",
                    "\n",
                    "    # Stage 4: Train ONCE\n",
                    "    print('  [Stage 4] Training models...')\n",
                    "    models = generate_oof_train(Xt_sm, y_sm, Xs_tr, y_tr, Xg_tr)\n",
                    "    print('  [Stage 4] Predicting OOF (val)...')\n",
                    "    oof_vl, best_lgb = predict_oof(models, Xt_vl, Xs_vl, Xg_vl)\n",
                    "    print('  [Stage 4] Predicting OOF (train)...')\n",
                    "    oof_tr, _ = predict_oof(models, Xt_tr, Xs_tr, Xg_tr)\n",
                    "\n",
                    "    # Stage 5: Meta\n",
                    "    meta, meta_p = stage5_meta(oof_tr, y_tr, oof_vl)\n",
                    "    auprc = average_precision_score(y_vl, meta_p)\n",
                    "    roc = roc_auc_score(y_vl, meta_p)\n",
                    "\n",
                    "    y_pred = (meta_p >= 0.5).astype(int)\n",
                    "    f1 = f1_score(y_vl, y_pred, zero_division=0)\n",
                    "    prec = precision_score(y_vl, y_pred, zero_division=0)\n",
                    "    rec = recall_score(y_vl, y_pred, zero_division=0)\n",
                    "\n",
                    "    fold_time = _time.time() - t_fold\n",
                    "    fold_metrics.append({'Fold': fold+1, 'AUPRC': auprc, 'ROC-AUC': roc,\n",
                    "                         'F1': f1, 'Precision': prec, 'Recall': rec,\n",
                    "                         'Time_min': fold_time/60})\n",
                    "    print(f'  FOLD {fold+1}: AUPRC={auprc:.4f}, ROC-AUC={roc:.4f}, F1={f1:.4f}, P={prec:.4f}, R={rec:.4f} ({fold_time/60:.1f}min)')\n",
                    "    del Xt_sm, y_sm; gc.collect()\n",
                    "\n",
                    "    if fold == 4:\n",
                    "        print(f'\\n{\"=\"*60}\\nFOLD 5 (FINAL): Detailed Metrics + XAI\\n{\"=\"*60}')\n",
                    "        print('\\n--- Classification Report ---')\n",
                    "        print(classification_report(y_vl, y_pred, target_names=['Normal', 'Fraud']))\n",
                    "        print('--- Confusion Matrix ---')\n",
                    "        cm = confusion_matrix(y_vl, y_pred)\n",
                    "        print(f'  TN={cm[0,0]:,}  FP={cm[0,1]:,}')\n",
                    "        print(f'  FN={cm[1,0]:,}  TP={cm[1,1]:,}')\n",
                    "        print(f'\\n--- Threshold Analysis ---')\n",
                    "        for t in [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]:\n",
                    "            yt = (meta_p >= t).astype(int)\n",
                    "            print(f'  t={t:.1f}: F1={f1_score(y_vl, yt, zero_division=0):.4f}, '\n",
                    "                  f'P={precision_score(y_vl, yt, zero_division=0):.4f}, '\n",
                    "                  f'R={recall_score(y_vl, yt, zero_division=0):.4f}')\n",
                    "\n",
                    "        Xs = Xt_vl[:200]\n",
                    "        top3 = stage6_xai(best_lgb, Xt_tr[:2000], Xs, selected)\n",
                    "        stage7_dual_output(meta_p, top3, y_vl)\n",
                    "        if df_meta is not None:\n",
                    "            stage8_hitl(meta_p, df_meta.iloc[vl_i])\n",
                    "\n",
                    "total_time = (_time.time() - t_start) / 60\n",
                    "print(f'\\n{\"=\"*60}\\nMVS-XAI IEEE-CIS Pipeline Complete\\n{\"=\"*60}')\n",
                    "mdf = pd.DataFrame(fold_metrics)\n",
                    "print(mdf.to_string(index=False))\n",
                    "print(f'\\nMean AUPRC:   {mdf[\"AUPRC\"].mean():.4f} +/- {mdf[\"AUPRC\"].std():.4f}')\n",
                    "print(f'Mean ROC-AUC: {mdf[\"ROC-AUC\"].mean():.4f} +/- {mdf[\"ROC-AUC\"].std():.4f}')\n",
                    "print(f'Mean F1:      {mdf[\"F1\"].mean():.4f} +/- {mdf[\"F1\"].std():.4f}')\n",
                    "print(f'Mean Prec:    {mdf[\"Precision\"].mean():.4f} +/- {mdf[\"Precision\"].std():.4f}')\n",
                    "print(f'Mean Recall:  {mdf[\"Recall\"].mean():.4f} +/- {mdf[\"Recall\"].std():.4f}')\n",
                    "print(f'Total runtime: {total_time:.1f} min')\n",
                ]
            print(f'  [{ds_name}] Pipeline: train-once + F1/P/R/CM + timing')

    with open(nb_file, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1)
    print(f'[SAVED] {nb_file}')

print('\n=== Both notebooks updated: Speed optimized + Full metrics ===')
